/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package caes;

public class Aes {
  public static byte[] intel_AES_enc128_char(byte[] plainText, byte[] cipherText, byte[] key, long numBlocks) {
    return AesJNI.intel_AES_enc128_char(plainText, cipherText, key, numBlocks);
  }

  public static byte[] intel_AES_dec128_char(byte[] cipherText, byte[] plainText, byte[] key, long numBlocks) {
    return AesJNI.intel_AES_dec128_char(cipherText, plainText, key, numBlocks);
  }

}
