/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package caes;

public class AesJNI {
  public final static native byte[] intel_AES_enc128_char(byte[] jarg1, byte[] jarg2, byte[] jarg3, long jarg4);
  public final static native byte[] intel_AES_dec128_char(byte[] jarg1, byte[] jarg2, byte[] jarg3, long jarg4);
}
